inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "vendor/**/*"
    - "spec/unit/fixtures/**/*"
    - "tmp/**/*"
    - "ansible-role-qa"
    - "lib/qansible_init/templates/**/*"
    - "qansible.gemspec"
  TargetRubyVersion: 2.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SpaceInsideBrackets:
  Enabled: false

Style/FormatString:
  Enabled: false

Metrics/ClassLength:
  Max: 200
